version: "3.1"

# bash into container docker exec -it user sh

services:
  scylla:
    container_name: scylla
    image: scylladb/scylla:5.0.1
    ports:
      - "9042:9042"
    volumes:
      - ./data/scylla:/var/lib/scylla/data


