// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"database/sql"

	"github.com/paulmach/orb"
)

type Party struct {
	ID              string
	UserID          string
	Title           string
	Description     sql.NullString
	IsPublic        bool
	MaxParticipants sql.NullInt32
	Location        orb.Point
	StreetAddress   sql.NullString
	PostalCode      sql.NullString
	State           sql.NullString
	Country         sql.NullString
	StartDate       sql.NullTime
	EndDate         sql.NullTime
}
