apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-service
spec:
  selector:
    matchLabels:
      app: party-service
  template:
    metadata:
      labels:
        app: party-service
    spec:
      containers:
        - name: party-service
          image: okteto.dev/party-service
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          command:
            - air
          ports:
            - containerPort: 8081
