apiVersion: apps/v1
kind: Deployment
metadata:
  name: relation
spec:
  selector:
    matchLabels:
      app: relation-service
  template:
    metadata:
      labels:
        app: relation-service
    spec:
      containers:
        - name: relation-service
          image: okteto.dev/relation-service
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          command:
            - air
          ports:
            - containerPort: 8081
