apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: okteto.dev/search-service
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
