apiVersion: apps/v1
kind: Deployment
metadata:
  name: story
spec:
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: okteto.dev/story-service
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
