// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repository

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	DeleteAccount(ctx context.Context, id string) error
	EmailTaken(ctx context.Context, email string) (bool, error)
	GetAccount(ctx context.Context, id string) (Account, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	UpdateEmailCode(ctx context.Context, arg UpdateEmailCodeParams) (Account, error)
	UpdateVerified(ctx context.Context, arg UpdateVerifiedParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
